### ISSUE TITLE
Catch error?

### ISSUE THREAD

**Issue by iamazik** [VinceG/vue-web-cam#1]
How would you catch the error when the user doesn't have a webcam?

**Comment by VinceG** [comment]
notsupported=“onUserHasNoWebcam”

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by iamazik** [comment]
@VinceG Can you please elaborate more or provide a complete example?

**Comment by VinceG** [comment]
The component will emit an even if there is no webcam detected, all you have to do is listen on that event.

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone
