### ISSUE TITLE
Electron & latest macOS Mojave

### ISSUE THREAD

**Issue by kieranbarlow** [VinceG/vue-web-cam#14]
Hi, this is no doubt nothing to do with your plugin as I've tested in the browser and everything works ok.

I have this plugin in my electron application which previously worked fine however after updating my macbook to the latest macOS Mojave it seems the application quits unexpectedly when getting to the component that uses the the vue-web-cam component. I've omitted this component and the page works as expected.

Have you come across this before? It seems like it's a permission issue with Mojave as they've bumped up the security.

**Comment by VinceG** [comment]
@Wolrab1 I use Mojave, however i never used Electron so i am not sure if that's the cause for the issue. Not sure if i can even troubleshot this since i don't use Electron. Is there an error log for this when it crashes ?
