### ISSUE TITLE
Back Camera undefined

### ISSUE THREAD

**Issue by iparrabb** [VinceG/vue-web-cam#15]
Hi,

Thanks for this awesome plugin :)

Front Camera works fine, but I'm having an issue when select the back camera from a device with the example code. Returns undefined most of the time, although it sometimes shows the correct camera, any idea? 

I'm testing with Android 6 and 8.1 and Chrome 69.0.3497.100 with the latest version of plugin ^1.3.0

PD: On Android 6 facing back camera never works, only return undefined...

Thanks!

**Comment by iparrabb** [comment]
@VinceG, any help please?

**Comment by VinceG** [comment]
And what exactly is the error message?

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by iparrabb** [comment]
You can see in my first message, camera is undefined...

**Comment by VinceG** [comment]
In order to be able to assist I’ll need an exact error message preferably with a stack trace or a repository with minimal setup to reproduce this 

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by iparrabb** [comment]
@VinceG, I attached a full example above with the code that I'm using, this error happens on Android 6 and Android 8 sometimes, is not enough?

```js
onError(error, stream) {
  console.log(error) //undefined
},
```

**Comment by VinceG** [comment]
@iparrabb Sorry, i can't run the example. I don't use Quasar and i don't have an android device or emulator to test this on.

If the demo works for you (as it does for me) there isn't much i can do to try and troubleshoot this with you since i don't have anything to test this on. Also the error you mentioned that appears is ambiguous, undefined can mean a lot of things, what exactly is undefined, is it the error variable passed in, the camera instance? you still haven't provided the entire stack trace or the exact error message, therefore there isn't much i can do, Sorry.

**Comment by iparrabb** [comment]
Hi @VinceG, the demo doesn't works on Android, it only works sometimes, the code that I am using is the demo code, you can see my example, only changes the dropdown, the rest is all the same.

Webcam fires the error event and this event fires the onError method on my component, and it receives two arguments, error and stream, error is undefined sometimes.

```html
<web-cam
       ref="webcam"
       width="100%"
       height="100%"
       :deviceId="deviceId"
       @started="onStarted"
       @stopped="onStopped"
       @error="onError" <!-- onError -->
       @cameras="onCameras"
       @camera-change="onCameraChange"
/>
```

```js
onError(error, stream) {
        console.log(error) // undefined sometimes on Android
},
```

Thanks.

**Comment by iparrabb** [comment]
@VinceG, thanks for your help.

You can see the [demo example](https://github.com/VinceG/vue-web-cam/blob/master/demo/src/main.vue):
```js
onError(error, stream) {
      console.log('On Error Event', error, stream);
},
````
I'm using the last version:
```js
"vue-web-cam": "^1.3.0",
````
Is very hard catch this error because only happens when runs on Android device. Tomorrow I will try to debug more about this.

**Comment by VinceG** [comment]
@iparrabb Sorry about that, the demo is wrong then, there is no stream argument. I'll fix that.

**Comment by GeNiuS69** [comment]
@iparrabb Did you solve your problem?
I had something similar. Try use this fork https://github.com/dsmlru/vue-web-cam
If it'll help you I'll create PR.

**Comment by iparrabb** [comment]
Thanks a lot @GeNiuS69, I test it tomorrow!

**Comment by GeNiuS69** [comment]
@iparrabb hey, did you test?
