### ISSUE TITLE
getUserMedia results in black screen on iOS 11.4 || >

### ISSUE THREAD

**Issue by iparrabb** [VinceG/vue-web-cam#16]
On iOS 11.4.1 the webcam request permissions but then show a black screen without image, any idea?

Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15A356 Safari/604.1

**Comment by VinceG** [comment]
@iparrabb Going to close this since OP didn't respond in 10 days.
