### ISSUE TITLE
Changes in the Demo Application

### ISSUE THREAD

**Issue by glaucia86** [VinceG/vue-web-cam#17]
Hi @VinceG.
I've been trying to make some good changes in the demo application. But no success once I don't have access rights. So I would like to ask you a permission to make these changes in the demo project.
If you want to, I can create a demo application on my handle GH account and then send you the project for you see it. What do you think about it?

Kind regards,

Glaucia Lemos

**Comment by VinceG** [comment]
Hey,

Yeah sure. Not entirely sure though what the changes are for?

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by glaucia86** [comment]
> Hey, Yeah sure. Not entirely sure though what the changes are for?
> […](#)
> ----- Vincent Gabriel Software Engineer Please excuse my brevity, sent from my iPhone
> On Nov 19, 2018, at 07:31, Glaucia Lemos ***@***.***> wrote: Hi @VinceG. I've been trying to make some good changes in the demo application. But no success once I don't have access rights. So I would like to ask you a permission to make these changes in the demo project. If you want to, I can create a demo application on my handle GH account and then send you the project for you see it. What do you think about it? Kind regards, Glaucia Lemos — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

@VinceG It would change the architecture in how the demo was developed. If you wish tonight I can develop a demo version, with separate files, routes and everything. Then I send the demo link as it was and in case you like how the demo was, I'll send you the project link. if you like and are approved, you can include in the official master project.

**Comment by VinceG** [comment]
@glaucia86 That works, yeah thank you.

**Comment by glaucia86** [comment]
@VinceG nice. As soon as posible I will send you the demo aplication for you. Thanks Vincent! :)
