### ISSUE TITLE
Cannot use web-cam component inside a q-modal component.

### ISSUE THREAD

**Issue by cbullokles** [VinceG/vue-web-cam#19]

**Comment by VinceG** [comment]
@cbullokles I don't know what a q-modal is.

**Comment by cbullokles** [comment]
> @cbullokles I don't know what a q-modal is.

It is a Quasar Modal Component:
https://quasar-framework.org/components/modal.html

**Comment by VinceG** [comment]
@cbullokles Not sure what i can do here since i don't really use Quasar framework, unless you can provide a simple repository where you can reproduce the issue.

**Comment by DespertaWeb** [comment]
@cbullokles In first hand I suggest you to provide always some code.

It's working for me (taking picture next to do):
https://pastebin.com/eDSRpvun
