### ISSUE TITLE
Broken on latest Safari

### ISSUE THREAD

**Issue by bramski** [VinceG/vue-web-cam#2]
<img width="1207" alt="screen shot 2018-06-04 at 12 53 13 pm" src="https://user-images.githubusercontent.com/421781/40938284-4bdf7706-67f6-11e8-880b-b6e2acbeaee0.png">

**Comment by bramski** [comment]
Basically this is not using the newest way you're supposed to access getUserMedia on safari... See:
https://github.com/eduardolundgren/tracking.js/issues/228

I'll issue a PR shortly.

**Comment by bramski** [comment]
Fixed by #3

**Comment by VinceG** [comment]
Thank You.
