### ISSUE TITLE
stream from the network

### ISSUE THREAD

**Issue by EduardShaid** [VinceG/vue-web-cam#32]
Will there be a stream from the network (not local webcam, but from the stream server) in the near future ?

**Comment by VinceG** [comment]
@EduardShaid how do you even do that? Is there documentation for that?

**Comment by EduardShaid** [comment]
Here is an example to practice.
https://www.youtube.com/watch?v=EbGPN95Vdgo

Here VLC works as a streaming server. You can take to enter not only the camera, but also ready-made files.

**Comment by VinceG** [comment]
@EduardShaid I don't think i'll be able to support this here. you can submit a PR if you can work on implementing this.
