### ISSUE TITLE
On Error Event Error: getUserMedia is not implemented in this browser

### ISSUE THREAD

**Issue by kevin8656** [VinceG/vue-web-cam#36]
![error](https://i.imgur.com/fVnC1hf.jpg)
I got some issue when i connect to my webcam
my webcam is use for the dentist to capture the teeth ,
but i dont know whan model is that camera
want to ask that how can i fix this issue?
thanks.

**Comment by VinceG** [comment]
@kevin8656 As the error states, looks like for some reason the getUserMedia is not implemented, even though it looks like you are using Chrome.

**Comment by kevin8656** [comment]
@VinceG Yes I'm using Chrome to do this,but it's not working .
Do you have any suggestion that how to make it work?
I use the pluggin named [webcamjs](https://github.com/jhuckaby/webcamjs)  can successfully use my cam for dentist to capture photo in html page.
But i don't know what's the different between this plugin and that for html.neet your suggestion. 
thanks a lot .

**Comment by VinceG** [comment]
@kevin8656 Yeah, i am really not sure. can you test with any other web cam?

**Comment by lilyrae** [comment]
@kevin8656 do you have HTTPS? I was also encountering this problem while on HTTP as Chrome doesn't allow `getUserMedia` when not from a secure context. (localhost should also be fine)

**Comment by kevin8656** [comment]
@lilyrae Yes,you're right. This problem is cause by HTTP is not Secure,so google chrome don't allow WebCam an Microphone to use.
I  host an server in local env, and use webcam locally.After i capture a photo , server will save the photo to the remote production server database.

**Comment by VinceG** [comment]
@kevin8656 Were you able to fix the issue?

**Comment by kevin8656** [comment]
@VinceG This issue could not be fix,the only way is to host the project with this plugin using https not http.
