### ISSUE TITLE
Error: "getUserMedia is not implemented in this browser"

### ISSUE THREAD

**Issue by sebastianro92** [VinceG/vue-web-cam#39]
Hi, good morning, I am getting the following error when running the component in the browser (chrome and firefox) 

On Error Event Error: getUserMedia is not implemented in this browser
    at Object.getUserMedia (app.js:50773)
    at VueComponent.testMediaAccess (app.js:50773)
    at VueComponent.setupMedia (app.js:50773)
    at VueComponent.mounted (app.js:50773)
    at invokeWithErrorHandling (app.js:52643)
    at callHook (app.js:54994)
    at Object.insert (app.js:53926)
    at invokeInsertHook (app.js:57115)
    at Vue.patch [as __patch__] (app.js:57332)
    at Vue._update (app.js:54720)

**Comment by sebastianro92** [comment]
@VinceG When i run navigator.getUserMedia in the console, this return "undefined"

**Comment by sebastianro92** [comment]
@VinceG I would like to clarify that this is happening when the component is running on my digitalocean server, when the component is running locally there are no problems.

**Comment by VinceG** [comment]
@sebastianro92 I don't know what that means, in both cases you are running it through a browser, right? If that returns undefined then the browser does not support it.

**Comment by sebastianro92** [comment]
@VinceG  The component runs correctly in the browsers I use, however it stops working when the component runs from my server in digitalocean

**Comment by VinceG** [comment]
@sebastianro92 How do you run it on your server? it won't work on the server since there is no access to the client media components. just like you won't be able to use 'fs' in the browser.

**Comment by sebastianro92** [comment]
@VinceG  I have a project developed in laravel (php) and I am using the vue components, the component on my local server (xampp) works correctly in any browser.

But when I execute my project from my server (DigitalOcean - Lamp) it generates the error described, at first it was not executed because I still do not have the SSL certificates on my digitalocean server, however, previously I could execute it without problems in Mozilla, but now I only show this in the console (Error Event Error: "getUserMedia is not implemented in this browser")

**Comment by VinceG** [comment]
Yeah, i mean if you run "navigator.getUserMedia" and it returns undefined that's the problem.

**Comment by VinceG** [comment]
@sebastianro92 Can you try running

```
navigator.mediaDevices.getUserMedia();
```

**Comment by sebastianro92** [comment]
@VinceG  When run navigator.mediaDevices.getUserMedia(); return this:

navigator.mediaDevices.getUserMedia();
Promise { "rejected" }
​
<state>: "rejected"
​
<reason>: Error: "getUserMedia is not implemented in this browser"
    legacyGetUserMediaSupport http://104.248.51.86/js/app.js:50773
    <anonymous> debugger eval code:1
​
<prototype>: PromiseProto

Browsers versions:

Firefox ver 69.0
Chrome ver 77.0

**Comment by VinceG** [comment]
@sebastianro92 And you are sure you are running that in the browser with SSL?
