### ISSUE TITLE
Helping with vue-web-cam

### ISSUE THREAD

**Issue by Giorat** [VinceG/vue-web-cam#4]
I have been working with your component in my project and I'd like to help you add some functions.

I have created a function to change camera so each time the user trigger the changeCamera( ) it's automatically changed the video stream, especially useful with mobile phones or tablets.

Here's the code, https://pastebin.com/rjULe7Ms

It's a little bit messy because I was trying to use the new browsers API that you just added in the past few days.

If you like my work with changeCamera(..) I'll do my best in the next few weeks to make a PR with a proposal or if you want you can already look at my code to start seeing how to implement different cameras on your own.

**Comment by VinceG** [comment]
@Giorat That'll be great. Lets try and collaborate to make this work. I also see that there is a warning in chrome about the use of "createObjectURL"

**Comment by Giorat** [comment]
I think createObjectURL is used only if the current browser doesn't support the new API.
Tonight I'll download your updated version and I'll try to add as many things as possible from my code and then I'll open a pull request! 😄

**Comment by Giorat** [comment]
@VinceG just pushed the pull request I'll close this issue now, let's talk in the PullRequest.
