### ISSUE TITLE
it shows empty block.

### ISSUE THREAD

**Issue by marko-mlinarevic** [VinceG/vue-web-cam#46]
```
<web-cam 
    ref="webcam"
    width="100%"
 />
```

I'm using nuxt. it generates
```
<video width="100%" height="500" autoplay="autoplay" playsinline="true"></video>
```
And its blank

when I try capture it gives me this as a string

```
data:
```

**Comment by VinceG** [comment]
@marko-mlinarevic You need to pass in :device-id prop, it's required. if you look at the JS console you'll see the warning.
