### ISSUE TITLE
Getting 'getUserMedia is not implemented in this browser'

### ISSUE THREAD

**Issue by helpcodemonkey** [VinceG/vue-web-cam#47]
Hi,

I'm receiving `getUserMedia is not implemented in this browser` from the error event when run on iOS chrome and firefox, but not on iOS safari, Android chrome and firefox.

I noticed that in `/src/webcam.vue`, line 114, you checked `if (navigator.mediaDevices.getUserMedia === undefined)`. Is this correct because `navigator.mediaDevices.getUserMedia` is a function that requires a constraint param and it returns a promise. reference: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by VinceG** [comment]
See #39

**Comment by helpcodemonkey** [comment]
> See #39

Hi, I have read issue #39. It’s running on a valid ssl cert and it’s working on Android mobile browser for both chrome and Firefox but not iOS chrome and Firefox.

**Comment by VinceG** [comment]
To confirm so i can test locally, this doesn't work on an iOS device on either Chrome or Firefox?

Any specific versions you are using so we can narrow this down?

**Comment by helpcodemonkey** [comment]
Yes doesn’t work on iOS for both chrome and Firefox. The versions are
79.0.3945.73 and 21.0(16918) for chrome and Firefox respectively.

**Comment by ddv1212** [comment]
I have the same problem @VinceG. On dev server everything works fine in all browsers but when I deploy with nginx on my raspberry pi in my local network i get the same error "Error: getUserMedia is not implemented in this browser"

Console: navigator.getUserMedia
Output: undefined

Console: navigator.mediaDevices.getUserMedia
Output: function legacyGetUserMediaSupport()

Console: navigator.mediaDevices.getUserMedia()
Output: Promise { <state>: "rejected" }

I tried everything I described on different clients with different browsers and os's.

Do you have an advice?

**Comment by ddv1212** [comment]
Solved the problem: getUserMedia is only callable if you running your application on localhost (the browser defines this as secure) OR use SSL at deployment. @VinceG Your code works well! Anyway, SOMETIMES the webcams cannot be listed. I tested Chrome, Firefox and Safari in the latest stable versions. ps: i used exactly your code.

Thank you!

**Comment by helpcodemonkey** [comment]
Hi ddv1212,

just to verify that it works for you on an iphone browser?

Best,
Chris

**Comment by ddv1212** [comment]
@helpcodemonkey I don't try it on an iPhone but Safari on latest OSX works well. I will try it from an iPhone the next days.

Regards

**Comment by helpcodemonkey** [comment]
Yea it works ok on osx for me too. Hope to hear from you soon.

Best,
Chris

**Comment by ddv1212** [comment]
@helpcodemonkey tested it on latest firmware of the iPhone 5s and it works pretty fine!

**Comment by helpcodemonkey** [comment]
Do you have a demo site that I can test on?

Best,
Chris

**Comment by Bibooo25730** [comment]
你好    
使用 https 协议
    客户端浏览器手动指定域名安全
在谷歌输入网址的地方输入
chrome://flags/#unsafely-treat-insecure-origin-as-secure
在里面配置指定域名，然后选择 select 为 enabled 然后重启，就解决问题啦
