### ISSUE TITLE
Is Vue3 Supported?

### ISSUE THREAD

**Issue by ABusyProgrammer** [VinceG/vue-web-cam#69]
I'm trying to use this dependency with my Vue 3 project, but I keep getting the error `TypeError: Cannot read property '_c' of undefined`. Upon searching online, this error comes when a dependency that only supports Vue 2 is used in a Vue 3 project. Is this the case here too?

**Comment by VinceG** [comment]
This does not work with vue 3

**Comment by danaki** [comment]
:(
